application: punspace
version: 2-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /api/subscribers/?
  script: subscriber.urls.app

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: webapp/static

- url: .*
  script: webapp.urls.app

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.2"

